name: EJC
on:
  push:
    branches: [ejc]

jobs:
  deploys:
    runs-on: ubuntu-latest
    steps:
      - name: EJC
        uses: zzzze/webhook-trigger@v1.0.0
        with:
          webhook_url: "https://pleskw.nspmanaged.com:8443/modules/git/public/web-hook.php?uuid=a8e259f5-1ae2-d503-460a-9944055833c3"
          json: '{ "repository": "${{github.event.repository.full_name}}", "number": "${{github.event.number}}", "created_at": "${{github.event.pull_request.created_at}}", "updated_at": "${{github.event.pull_request.updated_at}}" }'
      - name: EJC Recon
        uses: zzzze/webhook-trigger@v1.0.0
        with:
          webhook_url: "https://pleskw.nspmanaged.com:8443/modules/git/public/web-hook.php?uuid=c99ad24f-2a81-c33a-8b75-1912ae597c0b"
          json: '{ "repository": "${{github.event.repository.full_name}}", "number": "${{github.event.number}}", "created_at": "${{github.event.pull_request.created_at}}", "updated_at": "${{github.event.pull_request.updated_at}}" }'
      - name: Realidade Recon
        uses: zzzze/webhook-trigger@v1.0.0
        with:
          webhook_url: "https://pleskw.nspmanaged.com:8443/modules/git/public/web-hook.php?uuid=d2395dc3-38f8-57f2-690c-e64be51aab5b"
          json: '{ "repository": "${{github.event.repository.full_name}}", "number": "${{github.event.number}}", "created_at": "${{github.event.pull_request.created_at}}", "updated_at": "${{github.event.pull_request.updated_at}}" }'
